### ISSUE TITLE
include all repos for `organization/` listing

### ISSUE THREAD

**Issue by yarikoptic** [con/solidation#15]
I think in many cases, e.g `dandi/` and in principle could apply to original `datalad/` - it would be useful to allow for simply including all repos for the organization.  

An alternative could be to add support for regexes or globs, to sub-select some, but I do not have immediate usecase so not worth bothering I guess.

Also i am afraid that sooner than later we would run into the case desiring to exclude some repos, e.g.
- exclude public or private
- exclude based on some regex
but I think we can worry about exclusion when we get there.

getting repos seems to be easy
```
In [16]: org = gh.get_organization('dandi')

In [17]: [r.name for r in org.get_repos(type='all')]
Out[17]: 
['dandi.github.io',
 'dandi-infrastructure',
 'artwork',
 'dandisets',
 'dandi-cli',
 'dandiarchive-legacy',
 'dandi-hub',
 'z2jh-aws-ansible',
 'example-notebooks',
 'nwb-metadata-gui',
 'metadata-dumps',
 'ndx-dandi',
 'redirector',
 'dandi-core',
 'dandi-publish',
 'schema',
 'handbook',
 'neuroconv',
 'dandi-archive',
 'dandi-api-datasets',
 'dandi-api-webshots',
 'nwb-healthstatus',
 'helpdesk',
 'dandi-schema',
 'dandi-api-webshots-staging',
 'dandi-api-webshots-tools',
 'dandi-api-webshots-prs',
 '.github',
 'upload-benchmarks',
 'bids-examples',
 'dandisets-book',
 'rehack-book',
 'dandisets-healthstatus',
 'zarr_checksum']
```

**Comment by jwodder** [comment]
@yarikoptic So how should this be specified in the config file?  As an `organizations: [dandi, con, ...]` field, or by including globs like `dandi/*` in the `repositories` list?

**Comment by yarikoptic** [comment]
I thought just to have a convention , without even a glob, of using `dandi/` (ie without any particular repo as  `dandi/dandi-cli` ) to signal similar to glob `dandi/*`.  

Could be `organizations` as well I guess. Would make it easier later to make them into records to exclude stuff, e.g.
```yaml
organizations:
   - name: dandi 
   - name: datalad
     exclude: .*-ci
```
or alike.
