### ISSUE TITLE
Add Assigned Issues/PRs and "dynamics" in given reporting period.

### ISSUE THREAD

**Issue by yarikoptic** [con/solidation#29]
Compliment at the bottom with the section where for each member there would be per each member which would be pretty much an overview of individual assigned issues and PRs like 

- [yarikoptic](https://github.com/yarikoptic): [47](https://github.com/issues?q=assignee%3Ayarikoptic+is%3Aopen) = [45 issues](https://github.com/issues?q=assignee%3Ayarikoptic+is%3Aopen+type%3Aissue)/[2 PRs](https://github.com/issues?q=assignee%3Ayarikoptic+is%3Aopen+is%3Apr) [0 blocked](https://github.com/pulls?q=assignee%3Ayarikoptic+is%3Aopen+label%3A%22blocked%22) +???/-???

where `+???/-???` would be number of issues or PRs closed within the given time period. I don't think there is a query for that but I would assume could be estimated based on dates when issue/PR was assigned or created, or closed.

**Comment by jwodder** [comment]
@yarikoptic 

> where `+???/-???` would be number of issues or PRs closed within the given time period

Is `+???/-???` supposed to represent a single number?  When would it be negative?

**Comment by yarikoptic** [comment]
`+???` is for new assigned (may be even closed already, e.g. it was assigned Tue, closed Wed, then it should contribute to both + and -), `-???` is for how many addressed/closed

**Comment by jwodder** [comment]
@yarikoptic 

* Exactly what is the criteria for the `+???` number?  The GitHub REST API does not report the date at which issues & PRs were assigned.  Should it just be the number of issues/PRs created in the last `recent_days` days that are assigned to the given user?
* Similarly, should the `-???` number just be the number of issues/PRs closed in the last `recent_days` days that are assigned to the given user?

**Comment by jwodder** [comment]
@yarikoptic Also, is the "blocked" number supposed to count issues or PRs?  I would expect it to count both, but the link in your initial comment is for PRs only.

**Comment by yarikoptic** [comment]
> * Exactly what is the criteria for the `+???` number?  The GitHub REST API does not report the date at which issues & PRs were assigned.  Should it just be the number of issues/PRs created in the last `recent_days` days that are assigned to the given user?

ok, let's do that - at least those which are created and assigned shortly after would be covered.

> * Similarly, should the `-???` number just be the number of issues/PRs closed in the last `recent_days` days that are assigned to the given user?

yes then.

> @yarikoptic Also, is the "blocked" number supposed to count issues or PRs? I would expect it to count both, but the link in your initial comment is for PRs only.

I thought about both indeed.
